version: '3.9'

services:
  web:
    build: .
    image: juarezdaniei97/ecommerce_app:v1
    container_name: web
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
